Indent space: 2

diff --git a/pre-run b/pre-run
--- a/pre-run
+++ b/pre-run
@@ -14,8 +14,8 @@ VERBOSITY=1
 
 # Display a banner
 banner() {
-    printf "\n"
-    printf "Pre-run\n"
+  printf "\n"
+  printf "Pre-run\n"
 }
 
 # Usage of the script
@@ -30,87 +30,87 @@ usage() {
   printf "  Loan Lassalle - <https://github.com/lassalleloan>\n"
   printf "\n"
   printf "Options:\n"
-  printf "  -v, --verbosity (0 | 1 | 2)       Level of verbosity: no ouput, step information, interactive\n"
-  printf "  -h, --help                        Help on how to use this script\n"
+  printf "  -v, --verbosity (0 | 1 | 2)     Level of verbosity: no ouput, step information, interactive\n"
+  printf "  -h, --help                      Help on how to use this script\n"
 }
 
 # Check for updates
 check_updates() {
-    local current_version="$1"
-    local verbosity="$2"
+  local current_version="$1"
+  local verbosity="$2"
 
-    if [ "$verbosity" -ne 0 ]; then
-        printf "Checking for updates\n"
-    fi
+  if [ "$verbosity" -ne 0 ]; then
+    printf "Checking for updates\n"
+  fi
 
-    new_version="$(curl https://raw.githubusercontent.com/StevenBlack/hosts/master/package.json --silent | \
-        sed -En 's/^ *"version": *"([0-9]([.][0-9]*)*)",$/\1/p')"
+  new_version="$(curl https://raw.githubusercontent.com/StevenBlack/hosts/master/package.json --silent \
+    | sed -En 's/^ *"version": *"([0-9]([.][0-9]*)*)",$/\1/p')"
 
-    if [ "$verbosity" -eq 2 ]; then
-        printf "Current version: %*s\n" 12 $current_version
-        printf "Current version: %*s\n" 12 $new_version
-    fi
+  if [ "$verbosity" -eq 2 ]; then
+    printf "Current version: %*s\n" 12 $current_version
+    printf "Current version: %*s\n" 12 $new_version
+  fi
 
-    sed -i '' -E "/^# CURRENT_VERSION=([0-9]([.][0-9]*)*)$/s/$current_version/$new_version/" env.list
+  sed -i '' -E "/^# CURRENT_VERSION=([0-9]([.][0-9]*)*)$/s/$current_version/$new_version/" env.list
 
-    if [ -f src/hosts -a -s src/hosts -a "$new_version" == "$current_version" ]; then
-        exit 1
-    fi
+  if [ -f src/hosts -a -s src/hosts -a "$new_version" == "$current_version" ]; then
+    exit 1
+  fi
 }
 
 # Check if it is an integer
 exit_if_not_integer() {
-    local variable="$1"
+  local variable="$1"
 
-    if ! echo "$variable" | grep -Eq  "^[0-9]{1}$"; then
-        printf "%s: not a integer\n" $variable
-        usage
-        exit 1
-    fi
+  if ! echo "$variable" | grep -Eq  "^[0-9]{1}$"; then
+    printf "%s: not a integer\n" $variable
+    usage
+    exit 1
+  fi
 }
 
 # Main
 for arg in "$@"; do
-    shift
-    case "$arg" in
-        "--verbosity")
-            set -- "$@" "-v"
-            ;;
-        "--help")
-            set -- "$@" "-h"
-            ;;
-        "--"*)
-            set -- "$@" "-?"
-            ;;
-        *)
-            set -- "$@" "$arg"
-    esac
+  shift
+  case "$arg" in
+    "--verbosity")
+      set -- "$@" "-v"
+      ;;
+    "--help")
+      set -- "$@" "-h"
+      ;;
+    "--"*)
+      set -- "$@" "-?"
+      ;;
+    *)
+      set -- "$@" "$arg"
+  esac
 done
 
 while getopts ":v:h" option; do
-    case $option in
-        v)
-            VERBOSITY=$OPTARG
-            exit_if_not_integer "$VERBOSITY"
-            ;;
-        h)
-            usage
-            exit
-            ;;
-        :)
-            printf "%s: argument required\n" $OPTARG
-            exit 1
-            ;;
-        \?)
-            printf "%s: invalid option\n" $OPTARG
-            usage
-            exit 1
-            ;;
-    esac
+  case $option in
+    v)
+      VERBOSITY=$OPTARG
+      exit_if_not_integer "$VERBOSITY"
+      ;;
+    h)
+      usage
+      exit
+      ;;
+    :)
+      printf "%s: argument required\n" $OPTARG
+      exit 1
+      ;;
+    \?)
+      printf "%s: invalid option\n" $OPTARG
+      usage
+      exit 1
+      ;;
+  esac
 done
 
 if [ "$VERBOSITY" -ne 0 ]; then
-    banner
+  banner
 fi
 
 # Check for updates
